### ISSUE TITLE
[Request] Dark mode?

### ISSUE THREAD

**Issue by ItsNoted** [R4cc/Feedster#1]
Love the app! any plans to implement a dark mode? This is somewhere I spend a lot of time reading articles.

Thanks for the awesome app!

**Comment by R4cc** [comment]
Hello! A darkmode is currently in the works and you can "beta" test it by pulling the dev image instead of the latest. It should be refined and in the main branch by tomorrow!

**Comment by R4cc** [comment]
The darkmode has been implemented in the main branch and can be activated in the settings!
